
version: '2'

services:
  engine:
    image: moorkop/mccy-engine:$MCCY_TAG
    restart: always
    volumes_from:
      - docker-auth
    networks:
      - mccy-backend
      - mccy-assets
    command: >
      --security.user.password=$MCCY_PASSWORD
      --mccy.docker-host-uri=$DOCKER_HOST_URI
      --mccy.docker-cert-path=/carina/clusters/$CARINA_USERNAME/$DEPLOY_CLUSTER
      --mccy.deployment-powered-by.image-src=img/powered-by/powered-by-carina-wide.png
      --mccy.deployment-powered-by.href=https://getcarina.com/
      --mccy.assets.via=network
      --mccy.assets.network=${BRANCH}_mccy-assets
      --mccy.assets.my-name-on-network=mccy

  docker-auth:
    image: itzg/carina-cli
    environment:
      - CARINA_USERNAME
      - CARINA_APIKEY
    command: credentials $DEPLOY_CLUSTER

  proxy:
    image: moorkop/mccy-lets-nginx:master
    restart: always
    networks:
      - mccy-backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "constraint:node==*-n1"
      - "UPSTREAM=engine:8080"
      - "EMAIL=$LETSENCRYPT_EMAIL"
      - "DOMAIN=$LETSENCRYPT_DOMAIN"

networks:
  mccy-backend:
    driver: overlay
  mccy-assets:
    driver: overlay
